version: '3'

services:
  # webapp:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     DATABASE_URL: "postgresql://postgres:password@postgres:5432/mydatabase"
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8000:8000"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  postgres_data:
